### ISSUE TITLE
Invalid model

### ISSUE THREAD

**Issue by whikloj** [danloveg/NCTR-Bagit-Record-Transfer#6]
Running the `python3 manage.py migrate` script

```
> python3 manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, recordtransfer, sessions, sites
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying recordtransfer.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying sites.0001_initial... OK
  Applying sites.0002_alter_domain_unique... OK
INFO 2021-04-13 15:46:09,929 0002_auto_20200915_1007: transfer_user Group created
INFO 2021-04-13 15:46:09,930 0002_auto_20200915_1007: archivist_user Group created
  Applying recordtransfer.0002_auto_20200915_1007... OK
  Applying recordtransfer.0003_auto_20200915_1024... OK
  Applying recordtransfer.0004_auto_20200925_1149... OK
  Applying recordtransfer.0005_user_confirmed_email... OK
  Applying recordtransfer.0006_job... OK
  Applying recordtransfer.0007_auto_20201105_1322... OK
  Applying recordtransfer.0008_auto_20201105_1325... OK
  Applying recordtransfer.0009_auto_20201116_2033... OK
  Applying recordtransfer.0010_update_site_name... OK
  Applying recordtransfer.0011_archivist_permissions...Traceback (most recent call last):
  File "manage.py", line 23, in <module>
    main()
  File "manage.py", line 19, in main
    execute_from_command_line(sys.argv)
  File "/Users/whikloj/www/NCTR/NCTR-Bagit-Record-Transfer/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/Users/whikloj/www/NCTR/NCTR-Bagit-Record-Transfer/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/whikloj/www/NCTR/NCTR-Bagit-Record-Transfer/env/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/whikloj/www/NCTR/NCTR-Bagit-Record-Transfer/env/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/Users/whikloj/www/NCTR/NCTR-Bagit-Record-Transfer/env/lib/python3.8/site-packages/django/core/management/base.py", line 85, in wrapped
    res = handle_func(*args, **kwargs)
  File "/Users/whikloj/www/NCTR/NCTR-Bagit-Record-Transfer/env/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 243, in handle
    post_migrate_state = executor.migrate(
  File "/Users/whikloj/www/NCTR/NCTR-Bagit-Record-Transfer/env/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/Users/whikloj/www/NCTR/NCTR-Bagit-Record-Transfer/env/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/Users/whikloj/www/NCTR/NCTR-Bagit-Record-Transfer/env/lib/python3.8/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/Users/whikloj/www/NCTR/NCTR-Bagit-Record-Transfer/env/lib/python3.8/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/Users/whikloj/www/NCTR/NCTR-Bagit-Record-Transfer/env/lib/python3.8/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/Users/whikloj/www/NCTR/NCTR-Bagit-Record-Transfer/bagitobjecttransfer/recordtransfer/migrations/0011_archivist_permissions.py", line 29, in populate_permissions
    permission = Permission.objects.get(codename=codename)
  File "/Users/whikloj/www/NCTR/NCTR-Bagit-Record-Transfer/env/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/whikloj/www/NCTR/NCTR-Bagit-Record-Transfer/env/lib/python3.8/site-packages/django/db/models/query.py", line 429, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.DoesNotExist: Permission matching query does not exist.
```

Adding in a print statement it looks like it wants to load a Permission called `change_bag`. I don't know enough about Django to say but it looks like its trying to load a model. Which would be `Bag` I think.

Anyways, I'll leave this here.

**Comment by danloveg** [comment]
I just saw this as well and thought you might run into it, too. I'll be updating the docs with the fix, but I'll comment it here, too. Some of the permissions for the `auth` migration aren't created until _after_ the migration, which messes up the migrations that rely on those permissions existing. You'll want to run the `auth` migration first, then the full migration:

```
python3 manage.py migrate auth
python3 manage.py migrate
```

**Comment by whikloj** [comment]
Worked like a charm.

**Comment by whikloj** [comment]
So I tried to restart with a clean setup. 

Just for your information I still get a failure if I run the `python3 manage.py migrate auth` first. It appears like something in the full migrate needs to be triggered first then you run the auth migration. 🤷 

```
(env) [/Users/whikloj/www/NCTR/NCTR-Bagit-Record-Transfer/bagitobjecttransfer] 
> docker-compose -f docker-compose.dev.yml up -d
Creating network "bagitobjecttransfer_default" with the default driver
Creating redis_server_dev           ... done
Creating recordtransfer_mailhog_dev ... done
Creating recordtransfer_rq_workers_dev ... done

(env) [/Users/whikloj/www/NCTR/NCTR-Bagit-Record-Transfer/bagitobjecttransfer] 
> docker logs recordtransfer_rq_workers_dev
INFO 2021-04-14 11:41:53,570 worker: Worker rq:worker:8b284a80de114204b3acb98b3efd20d7: started, version 1.5.2
INFO 2021-04-14 11:41:53,570 worker: *** Listening on default...
INFO 2021-04-14 11:41:53,572 worker: Cleaning registries for queue: default

(env) [/Users/whikloj/www/NCTR/NCTR-Bagit-Record-Transfer/bagitobjecttransfer] 
> python3 manage.py migrate auth
Operations to perform:
  Apply all migrations: auth
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK

(env) [/Users/whikloj/www/NCTR/NCTR-Bagit-Record-Transfer/bagitobjecttransfer] 
> python3 manage.py migrate     
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, recordtransfer, sessions, sites
Running migrations:
  Applying recordtransfer.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying sites.0001_initial... OK
  Applying sites.0002_alter_domain_unique... OK
INFO 2021-04-14 11:42:21,097 0002_auto_20200915_1007: transfer_user Group created
INFO 2021-04-14 11:42:21,097 0002_auto_20200915_1007: archivist_user Group created
  Applying recordtransfer.0002_auto_20200915_1007... OK
  Applying recordtransfer.0003_auto_20200915_1024... OK
  Applying recordtransfer.0004_auto_20200925_1149... OK
  Applying recordtransfer.0005_user_confirmed_email... OK
  Applying recordtransfer.0006_job... OK
  Applying recordtransfer.0007_auto_20201105_1322... OK
  Applying recordtransfer.0008_auto_20201105_1325... OK
  Applying recordtransfer.0009_auto_20201116_2033... OK
  Applying recordtransfer.0010_update_site_name... OK
  Applying recordtransfer.0011_archivist_permissions...Traceback (most recent call last):
  File "manage.py", line 23, in <module>
    main()
  File "manage.py", line 19, in main
    execute_from_command_line(sys.argv)
  File "/Users/whikloj/www/NCTR/NCTR-Bagit-Record-Transfer/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/Users/whikloj/www/NCTR/NCTR-Bagit-Record-Transfer/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/whikloj/www/NCTR/NCTR-Bagit-Record-Transfer/env/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/whikloj/www/NCTR/NCTR-Bagit-Record-Transfer/env/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/Users/whikloj/www/NCTR/NCTR-Bagit-Record-Transfer/env/lib/python3.8/site-packages/django/core/management/base.py", line 85, in wrapped
    res = handle_func(*args, **kwargs)
  File "/Users/whikloj/www/NCTR/NCTR-Bagit-Record-Transfer/env/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 243, in handle
    post_migrate_state = executor.migrate(
  File "/Users/whikloj/www/NCTR/NCTR-Bagit-Record-Transfer/env/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/Users/whikloj/www/NCTR/NCTR-Bagit-Record-Transfer/env/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/Users/whikloj/www/NCTR/NCTR-Bagit-Record-Transfer/env/lib/python3.8/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/Users/whikloj/www/NCTR/NCTR-Bagit-Record-Transfer/env/lib/python3.8/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/Users/whikloj/www/NCTR/NCTR-Bagit-Record-Transfer/env/lib/python3.8/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/Users/whikloj/www/NCTR/NCTR-Bagit-Record-Transfer/bagitobjecttransfer/recordtransfer/migrations/0011_archivist_permissions.py", line 29, in populate_permissions
    permission = Permission.objects.get(codename=codename)
  File "/Users/whikloj/www/NCTR/NCTR-Bagit-Record-Transfer/env/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/whikloj/www/NCTR/NCTR-Bagit-Record-Transfer/env/lib/python3.8/site-packages/django/db/models/query.py", line 429, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.DoesNotExist: Permission matching query does not exist.
```

But then running the auth migration and full works
```
(env) [/Users/whikloj/www/NCTR/NCTR-Bagit-Record-Transfer/bagitobjecttransfer] 
> python3 manage.py migrate auth
Operations to perform:
  Apply all migrations: auth
Running migrations:
  No migrations to apply.

(env) [/Users/whikloj/www/NCTR/NCTR-Bagit-Record-Transfer/bagitobjecttransfer] 
> python3 manage.py migrate     
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, recordtransfer, sessions, sites
Running migrations:
  Applying recordtransfer.0011_archivist_permissions... OK
  Applying sessions.0001_initial... OK
```

**Comment by danloveg** [comment]
So are you saying that you ran:

```
python3 manage.py migrate
python3 manage.py migrate auth
python3 manage.py migrate
```

to make it work? I'm just a bit confused by your comment.

**Comment by whikloj** [comment]
I ran

```
python3 manage.py migrate auth
python3 manage.py migrate
```
But I got the error anyways, so then ran
```
python3 manage.py migrate auth
python3 manage.py migrate
```

Again.

I thought that running the `migrate auth` first would allow me to run the
`migrate` without an error. But I'm guessing there is more to this.
